version: '3.9'
services:

    db:
        container_name: gestoriabasededatosapi
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "14033:1433"
        environment:
               ACCEPT_EULA: "Y"
               SA_PASSWORD: "Paikon0709"
               MSSQL_PID: Express
        restart: always
    app:
         container_name: gestoriaapinet
         build: .
         depends_on:
             - db
         environment:
           DBServer: "db"
         ports: [8080:80] 
         restart: always
                 
    gestoriafrontend:
         container_name: gestoriafrontend
         build: 
               context: C:/Users/axel.picon/Desktop/employee/
               dockerfile: C:/Users/axel.picon/Desktop/employee/Dockerfile
         depends_on:
             - app            
         volumes:
                 - 'C:/Users/axel.picon/Desktop/employee:/app'
                 - '/app/node_modules'
         ports:
                - 3000:3000
         restart: always



